-- v109 — the uncle stocks up
--
-- Run this once in the Supabase SQL editor, after v108. Running it again is
-- safe (see the note on numbers changed by hand, below).
--
-- Nothing on the site uses this yet. It changes no table and no function:
-- only what `town_catalog` says of the game, which the town's rules read
-- (v106: "the numbers come from the code, and are kept here").
--
-- v106 to v108 wrote the catalog as the code had it when they ran, on
-- 2026-10-03. The same evening the owner asked for more, and the code has it
-- now; the database still has the morning's:
--
--   · twenty-five dishes of five other countries, five each ("ตอนนี้มีแต่สูตรอาหาร
--     ไทย ช่วยเอาอาหารประเทศอื่นที่ดังๆ มาด้วย ซัก 5 ประเทศ ประเทสละ 5 menu จะเพิ่ม อุปกรณ์ด้วย
--     ก็ได้"): sushi, ramen, pizza, bibimbap, naan and the rest; what they take
--     that the village did not have (seaweed, tofu, cheese, milk, fresh
--     noodles) and what they are cooked in (a rolling pin, a bamboo mat, a
--     stone bowl, a clay oven). Flour came down a tier for them;
--   · a recipe scroll for every dish that is cooked, sixty more ("อาหารมีหลาย
--     อย่างมาก ทำไมม้วนสูตรมีแค่ 6 อัน"): the uncle still sells six; the rest are to
--     be found in what the river brings up, which a later file will see to;
--   · his relatives no longer buy clay pots: a pot comes with every dish now
--     ("ช่วยเอาเงื่อนไข หม้อเปล่าในการทำอาหารออกไปเลย"), and a pot that fetched coins would
--     be coins for every dish cooked;
--   · so his shelf opens in another order, his orders may ask for more
--     things, and there are more hints to sell.
--
-- Seven of the catalog's thirteen rows say those things: items, goods, shelf,
-- order, hints, dishes, scrolls. This file writes all seven again, whole.
--
-- A NUMBER CHANGED BY HAND. v106 to v108 add a row only where there is none
-- (`on conflict do nothing`), so that a number an admin has changed outlives
-- the file being run twice. This one cannot be so polite: its whole purpose
-- is to replace what is there, so it writes OVER those seven rows. Nobody has
-- changed one by hand (there is no page for it yet, and nothing on the site
-- calls the town's functions), so nothing is lost today. If that is ever not
-- so, the first query at the foot says which rows were touched and when:
-- look before running. The other six rows (rules, carries, stamina, fish,
-- flotsam, fishing) are not touched, here or by running it again.
--
-- Nobody has a purse with anything in it and the village has opened nothing
-- (the second query at the foot shows it), so no bag holds a thing whose
-- meaning changes, and the shelf's new order moves nothing anybody has
-- already opened.

/* ── the numbers ─────────────────────────────────────────────────────────── */

-- <catalog:v109> written from lib/town/catalog.ts (npm test checks it; TOWN_WRITE=1 npx vitest run lib/town/catalog.test.ts writes it)
insert into public.town_catalog (key, data) values
  ('items', $town${
    "rod": {"kind":"tool","tier":1,"stack":1,"pays":30},
    "hoe": {"kind":"tool","tier":1,"stack":1,"pays":25},
    "can": {"kind":"tool","tier":1,"stack":1,"pays":20},
    "pot": {"kind":"tool","tier":1,"stack":1,"pays":0},
    "pan": {"kind":"tool","tier":1,"stack":1,"pays":35},
    "grill": {"kind":"tool","tier":1,"stack":1,"pays":30},
    "potFull": {"kind":"tool","tier":1,"stack":1,"pays":0},
    "bucket": {"kind":"tool","tier":1,"stack":1,"pays":8},
    "worm": {"kind":"bait","tier":1,"stack":20,"pays":1},
    "dough": {"kind":"bait","tier":1,"stack":20,"pays":1},
    "rice": {"kind":"staple","tier":1,"stack":20,"pays":1},
    "salt": {"kind":"staple","tier":1,"stack":20,"pays":1},
    "seedKangkong": {"kind":"seed","tier":1,"stack":10,"pays":2},
    "seedScallion": {"kind":"seed","tier":1,"stack":10,"pays":2},
    "seedCabbage": {"kind":"seed","tier":1,"stack":10,"pays":4},
    "seedCarrot": {"kind":"seed","tier":1,"stack":10,"pays":4},
    "seedDaikon": {"kind":"seed","tier":1,"stack":10,"pays":5},
    "seedCorn": {"kind":"seed","tier":1,"stack":10,"pays":6},
    "seedChili": {"kind":"seed","tier":1,"stack":10,"pays":5},
    "seedTomato": {"kind":"seed","tier":1,"stack":10,"pays":7},
    "seedBasil": {"kind":"seed","tier":1,"stack":10,"pays":4},
    "seedSweetPotato": {"kind":"seed","tier":1,"stack":10,"pays":7},
    "seedGarlic": {"kind":"seed","tier":1,"stack":10,"pays":5},
    "seedPumpkin": {"kind":"seed","tier":1,"stack":10,"pays":12},
    "kangkong": {"kind":"crop","tier":1,"stack":20,"pays":3},
    "scallion": {"kind":"crop","tier":1,"stack":20,"pays":3},
    "cabbage": {"kind":"crop","tier":1,"stack":10,"pays":20},
    "carrot": {"kind":"crop","tier":1,"stack":20,"pays":8},
    "daikon": {"kind":"crop","tier":1,"stack":10,"pays":18},
    "corn": {"kind":"crop","tier":1,"stack":20,"pays":14},
    "chili": {"kind":"crop","tier":1,"stack":20,"pays":5},
    "tomato": {"kind":"crop","tier":1,"stack":20,"pays":8},
    "basil": {"kind":"crop","tier":1,"stack":20,"pays":4},
    "sweetPotato": {"kind":"crop","tier":1,"stack":20,"pays":12},
    "garlic": {"kind":"crop","tier":1,"stack":20,"pays":10},
    "pumpkin": {"kind":"crop","tier":1,"stack":5,"pays":110},
    "minnow": {"kind":"fish","tier":1,"stack":20,"pays":3},
    "barb": {"kind":"fish","tier":1,"stack":10,"pays":8},
    "tilapia": {"kind":"fish","tier":1,"stack":10,"pays":10},
    "perch": {"kind":"fish","tier":1,"stack":10,"pays":9},
    "catfish": {"kind":"fish","tier":1,"stack":10,"pays":12},
    "pangasius": {"kind":"fish","tier":1,"stack":5,"pays":22},
    "snakehead": {"kind":"fish","tier":1,"stack":5,"pays":30},
    "eel": {"kind":"fish","tier":1,"stack":5,"pays":28},
    "prawn": {"kind":"fish","tier":1,"stack":10,"pays":35},
    "featherback": {"kind":"fish","tier":1,"stack":5,"pays":40},
    "goby": {"kind":"fish","tier":1,"stack":5,"pays":60},
    "koi": {"kind":"fish","tier":1,"stack":1,"pays":300},
    "hyacinth": {"kind":"catch","tier":1,"stack":20,"pays":2},
    "boot": {"kind":"catch","tier":1,"stack":5,"pays":0},
    "fishSauce": {"kind":"goods","tier":1,"stack":10,"pays":12},
    "compost": {"kind":"goods","tier":1,"stack":20,"pays":4},
    "growFert": {"kind":"goods","tier":1,"stack":20,"pays":10},
    "guardFert": {"kind":"goods","tier":1,"stack":20,"pays":12},
    "pestCure": {"kind":"goods","tier":1,"stack":10,"pays":10},
    "basket": {"kind":"goods","tier":1,"stack":1,"pays":0},
    "riceBox": {"kind":"dish","tier":1,"stack":5,"pays":3},
    "oddDish": {"kind":"dish","tier":1,"stack":5,"pays":0},
    "friedMinnow": {"kind":"dish","tier":1,"stack":5,"pays":12},
    "grilledFish": {"kind":"dish","tier":1,"stack":5,"pays":16},
    "grilledCorn": {"kind":"dish","tier":1,"stack":5,"pays":18},
    "roastSweetPotato": {"kind":"dish","tier":1,"stack":5,"pays":16},
    "stirKangkong": {"kind":"dish","tier":1,"stack":5,"pays":12},
    "basilCatfish": {"kind":"dish","tier":1,"stack":5,"pays":18},
    "tomYum": {"kind":"dish","tier":1,"stack":5,"pays":22},
    "sourCurry": {"kind":"dish","tier":1,"stack":5,"pays":20},
    "friedPerch": {"kind":"dish","tier":1,"stack":5,"pays":22},
    "fishCake": {"kind":"dish","tier":1,"stack":5,"pays":22},
    "spicyEel": {"kind":"dish","tier":1,"stack":5,"pays":26},
    "grilledPrawn": {"kind":"dish","tier":1,"stack":5,"pays":44},
    "steamedGoby": {"kind":"dish","tier":1,"stack":5,"pays":38},
    "pumpkinSoup": {"kind":"dish","tier":1,"stack":5,"pays":30},
    "shabu": {"kind":"dish","tier":1,"stack":10,"pays":30},
    "scrollFriedMinnow": {"kind":"scroll","tier":1,"stack":1,"pays":0},
    "scrollGrilledFish": {"kind":"scroll","tier":1,"stack":1,"pays":0},
    "scrollGrilledCorn": {"kind":"scroll","tier":1,"stack":1,"pays":10},
    "scrollRoastSweetPotato": {"kind":"scroll","tier":1,"stack":1,"pays":10},
    "scrollStirKangkong": {"kind":"scroll","tier":1,"stack":1,"pays":10},
    "scrollBasilCatfish": {"kind":"scroll","tier":1,"stack":1,"pays":10},
    "scrollTomYum": {"kind":"scroll","tier":1,"stack":1,"pays":10},
    "scrollSourCurry": {"kind":"scroll","tier":1,"stack":1,"pays":10},
    "scrollFriedPerch": {"kind":"scroll","tier":1,"stack":1,"pays":10},
    "scrollFishCake": {"kind":"scroll","tier":1,"stack":1,"pays":10},
    "scrollSpicyEel": {"kind":"scroll","tier":1,"stack":1,"pays":10},
    "scrollGrilledPrawn": {"kind":"scroll","tier":1,"stack":1,"pays":10},
    "scrollSteamedGoby": {"kind":"scroll","tier":1,"stack":1,"pays":10},
    "scrollPumpkinSoup": {"kind":"scroll","tier":1,"stack":1,"pays":10},
    "scrollShabu": {"kind":"scroll","tier":1,"stack":1,"pays":10},
    "rodTeak": {"kind":"tool","tier":2,"stack":1,"pays":90},
    "floatQuill": {"kind":"tool","tier":2,"stack":1,"pays":40},
    "hookSteel": {"kind":"tool","tier":2,"stack":1,"pays":40},
    "lineBraid": {"kind":"tool","tier":2,"stack":1,"pays":40},
    "netSmall": {"kind":"tool","tier":2,"stack":1,"pays":45},
    "hoeIron": {"kind":"tool","tier":2,"stack":1,"pays":75},
    "canCopper": {"kind":"tool","tier":2,"stack":1,"pays":60},
    "sickle": {"kind":"tool","tier":2,"stack":1,"pays":50},
    "krabung": {"kind":"tool","tier":2,"stack":1,"pays":0},
    "mortar": {"kind":"tool","tier":2,"stack":1,"pays":55},
    "steamer": {"kind":"tool","tier":2,"stack":1,"pays":70},
    "cleaver": {"kind":"tool","tier":2,"stack":1,"pays":55},
    "jar": {"kind":"tool","tier":2,"stack":1,"pays":45},
    "wok": {"kind":"tool","tier":2,"stack":1,"pays":80},
    "rollingPin": {"kind":"tool","tier":2,"stack":1,"pays":45},
    "sushiMat": {"kind":"tool","tier":2,"stack":1,"pays":50},
    "stoneBowl": {"kind":"tool","tier":2,"stack":1,"pays":70},
    "bowl": {"kind":"tool","tier":1,"stack":1,"pays":3},
    "potDirty": {"kind":"tool","tier":1,"stack":1,"pays":0},
    "scrubber": {"kind":"goods","tier":1,"stack":10,"pays":1},
    "ash": {"kind":"goods","tier":1,"stack":10,"pays":1},
    "bucketIron": {"kind":"tool","tier":2,"stack":1,"pays":30},
    "brush": {"kind":"tool","tier":2,"stack":1,"pays":25},
    "soap": {"kind":"goods","tier":2,"stack":10,"pays":3},
    "apron": {"kind":"tool","tier":2,"stack":1,"pays":40},
    "cricket": {"kind":"bait","tier":2,"stack":20,"pays":2},
    "branBait": {"kind":"bait","tier":2,"stack":20,"pays":2},
    "shrimpLive": {"kind":"bait","tier":2,"stack":20,"pays":3},
    "sugar": {"kind":"staple","tier":2,"stack":20,"pays":3},
    "oil": {"kind":"staple","tier":2,"stack":20,"pays":3},
    "tamarind": {"kind":"staple","tier":2,"stack":20,"pays":2},
    "egg": {"kind":"staple","tier":2,"stack":20,"pays":3},
    "flour": {"kind":"staple","tier":2,"stack":20,"pays":3},
    "seaweed": {"kind":"staple","tier":2,"stack":20,"pays":3},
    "tofu": {"kind":"staple","tier":2,"stack":20,"pays":3},
    "seedEggplant": {"kind":"seed","tier":2,"stack":10,"pays":8},
    "seedCucumber": {"kind":"seed","tier":2,"stack":10,"pays":7},
    "seedLongBean": {"kind":"seed","tier":2,"stack":10,"pays":7},
    "seedLemongrass": {"kind":"seed","tier":2,"stack":10,"pays":9},
    "seedGalangal": {"kind":"seed","tier":2,"stack":10,"pays":12},
    "seedLime": {"kind":"seed","tier":2,"stack":5,"pays":30},
    "seedPapaya": {"kind":"seed","tier":2,"stack":10,"pays":14},
    "eggplant": {"kind":"crop","tier":2,"stack":20,"pays":14},
    "cucumber": {"kind":"crop","tier":2,"stack":20,"pays":10},
    "longBean": {"kind":"crop","tier":2,"stack":20,"pays":9},
    "lemongrass": {"kind":"crop","tier":2,"stack":20,"pays":12},
    "galangal": {"kind":"crop","tier":2,"stack":20,"pays":22},
    "lime": {"kind":"crop","tier":2,"stack":20,"pays":10},
    "papaya": {"kind":"crop","tier":2,"stack":10,"pays":26},
    "gourami": {"kind":"fish","tier":2,"stack":10,"pays":12},
    "crab": {"kind":"fish","tier":2,"stack":10,"pays":10},
    "snail": {"kind":"fish","tier":2,"stack":20,"pays":2},
    "hampala": {"kind":"fish","tier":2,"stack":5,"pays":34},
    "sheatfish": {"kind":"fish","tier":2,"stack":5,"pays":42},
    "bagrid": {"kind":"fish","tier":2,"stack":5,"pays":36},
    "giantGourami": {"kind":"fish","tier":2,"stack":5,"pays":44},
    "frog": {"kind":"fish","tier":2,"stack":10,"pays":20},
    "tigerfish": {"kind":"fish","tier":2,"stack":5,"pays":90},
    "wallago": {"kind":"fish","tier":2,"stack":5,"pays":110},
    "driftwood": {"kind":"catch","tier":2,"stack":10,"pays":3},
    "bottle": {"kind":"catch","tier":2,"stack":10,"pays":2},
    "driedFish": {"kind":"goods","tier":2,"stack":10,"pays":14},
    "saltedFish": {"kind":"goods","tier":2,"stack":10,"pays":18},
    "curryPaste": {"kind":"goods","tier":2,"stack":10,"pays":20},
    "pickle": {"kind":"goods","tier":2,"stack":10,"pays":16},
    "charcoal": {"kind":"goods","tier":2,"stack":20,"pays":4},
    "rope": {"kind":"goods","tier":2,"stack":10,"pays":8},
    "manure": {"kind":"goods","tier":2,"stack":20,"pays":5},
    "noodle": {"kind":"goods","tier":2,"stack":20,"pays":6},
    "somTam": {"kind":"dish","tier":2,"stack":5,"pays":24},
    "grilledEggplant": {"kind":"dish","tier":2,"stack":5,"pays":20},
    "tomKha": {"kind":"dish","tier":2,"stack":5,"pays":40},
    "friedGourami": {"kind":"dish","tier":2,"stack":5,"pays":26},
    "crabCurry": {"kind":"dish","tier":2,"stack":5,"pays":44},
    "steamedSheatfish": {"kind":"dish","tier":2,"stack":5,"pays":46},
    "friedFrog": {"kind":"dish","tier":2,"stack":5,"pays":34},
    "laab": {"kind":"dish","tier":2,"stack":5,"pays":42},
    "omelette": {"kind":"dish","tier":2,"stack":5,"pays":14},
    "snailCurry": {"kind":"dish","tier":2,"stack":5,"pays":36},
    "candiedPumpkin": {"kind":"dish","tier":2,"stack":5,"pays":30},
    "friedRice": {"kind":"dish","tier":2,"stack":5,"pays":26},
    "sushi": {"kind":"dish","tier":2,"stack":5,"pays":34},
    "tempura": {"kind":"dish","tier":2,"stack":5,"pays":32},
    "okonomiyaki": {"kind":"dish","tier":2,"stack":5,"pays":34},
    "kimchi": {"kind":"dish","tier":2,"stack":5,"pays":18},
    "bibimbap": {"kind":"dish","tier":2,"stack":5,"pays":44},
    "kimbap": {"kind":"dish","tier":2,"stack":5,"pays":30},
    "pajeon": {"kind":"dish","tier":2,"stack":5,"pays":26},
    "harGow": {"kind":"dish","tier":2,"stack":5,"pays":34},
    "springRoll": {"kind":"dish","tier":2,"stack":5,"pays":24},
    "congee": {"kind":"dish","tier":2,"stack":5,"pays":30},
    "spaghetti": {"kind":"dish","tier":2,"stack":5,"pays":40},
    "minestrone": {"kind":"dish","tier":2,"stack":5,"pays":28},
    "samosa": {"kind":"dish","tier":2,"stack":5,"pays":26},
    "scrollSomTam": {"kind":"scroll","tier":2,"stack":1,"pays":0},
    "scrollOmelette": {"kind":"scroll","tier":2,"stack":1,"pays":0},
    "scrollGrilledEggplant": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollTomKha": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollFriedGourami": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollCrabCurry": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollSteamedSheatfish": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollFriedFrog": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollLaab": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollSnailCurry": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollCandiedPumpkin": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollFriedRice": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollSushi": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollTempura": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollOkonomiyaki": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollKimchi": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollBibimbap": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollKimbap": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollPajeon": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollHarGow": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollSpringRoll": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollCongee": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollSpaghetti": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollMinestrone": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "scrollSamosa": {"kind":"scroll","tier":2,"stack":1,"pays":20},
    "rodMaster": {"kind":"tool","tier":3,"stack":1,"pays":220},
    "floatBell": {"kind":"tool","tier":3,"stack":1,"pays":90},
    "hookTwin": {"kind":"tool","tier":3,"stack":1,"pays":90},
    "lineSilk": {"kind":"tool","tier":3,"stack":1,"pays":90},
    "netLong": {"kind":"tool","tier":3,"stack":1,"pays":100},
    "hoeSteel": {"kind":"tool","tier":3,"stack":1,"pays":160},
    "canBrass": {"kind":"tool","tier":3,"stack":1,"pays":140},
    "shears": {"kind":"tool","tier":3,"stack":1,"pays":110},
    "yoke": {"kind":"tool","tier":3,"stack":1,"pays":0},
    "potBrass": {"kind":"tool","tier":3,"stack":1,"pays":180},
    "stoveBig": {"kind":"tool","tier":3,"stack":1,"pays":150},
    "panBrass": {"kind":"tool","tier":3,"stack":1,"pays":170},
    "steamerBamboo": {"kind":"tool","tier":3,"stack":1,"pays":130},
    "hotpot": {"kind":"tool","tier":3,"stack":1,"pays":200},
    "oven": {"kind":"tool","tier":3,"stack":1,"pays":240},
    "ladle": {"kind":"tool","tier":3,"stack":1,"pays":20},
    "tok": {"kind":"tool","tier":3,"stack":1,"pays":60},
    "antEggs": {"kind":"bait","tier":3,"stack":20,"pays":6},
    "lure": {"kind":"bait","tier":3,"stack":5,"pays":30},
    "fermentedBait": {"kind":"bait","tier":3,"stack":20,"pays":5},
    "stickyRice": {"kind":"staple","tier":3,"stack":20,"pays":3},
    "soy": {"kind":"staple","tier":3,"stack":20,"pays":5},
    "pepper": {"kind":"staple","tier":3,"stack":20,"pays":6},
    "cheese": {"kind":"staple","tier":3,"stack":20,"pays":6},
    "milk": {"kind":"staple","tier":3,"stack":20,"pays":4},
    "seedMango": {"kind":"seed","tier":3,"stack":5,"pays":40},
    "seedBanana": {"kind":"seed","tier":3,"stack":5,"pays":25},
    "seedCoconut": {"kind":"seed","tier":3,"stack":5,"pays":45},
    "seedGinger": {"kind":"seed","tier":3,"stack":10,"pays":16},
    "seedTurmeric": {"kind":"seed","tier":3,"stack":10,"pays":16},
    "seedTaro": {"kind":"seed","tier":3,"stack":10,"pays":18},
    "seedWatermelon": {"kind":"seed","tier":3,"stack":10,"pays":20},
    "mango": {"kind":"crop","tier":3,"stack":20,"pays":30},
    "banana": {"kind":"crop","tier":3,"stack":20,"pays":16},
    "coconut": {"kind":"crop","tier":3,"stack":10,"pays":34},
    "ginger": {"kind":"crop","tier":3,"stack":20,"pays":26},
    "turmeric": {"kind":"crop","tier":3,"stack":20,"pays":26},
    "taro": {"kind":"crop","tier":3,"stack":10,"pays":30},
    "watermelon": {"kind":"crop","tier":3,"stack":5,"pays":60},
    "croaker": {"kind":"fish","tier":3,"stack":5,"pays":70},
    "blackEar": {"kind":"fish","tier":3,"stack":5,"pays":80},
    "spinyEel": {"kind":"fish","tier":3,"stack":5,"pays":60},
    "puffer": {"kind":"fish","tier":3,"stack":10,"pays":25},
    "goldenCarp": {"kind":"fish","tier":3,"stack":5,"pays":180},
    "giantSnakehead": {"kind":"fish","tier":3,"stack":5,"pays":200},
    "royalFeatherback": {"kind":"fish","tier":3,"stack":5,"pays":190},
    "arowana": {"kind":"fish","tier":3,"stack":1,"pays":600},
    "stingray": {"kind":"fish","tier":3,"stack":1,"pays":700},
    "megaCatfish": {"kind":"fish","tier":3,"stack":1,"pays":800},
    "pearl": {"kind":"catch","tier":3,"stack":10,"pays":150},
    "chest": {"kind":"catch","tier":3,"stack":1,"pays":0},
    "coconutMilk": {"kind":"goods","tier":3,"stack":10,"pays":22},
    "fermentedFish": {"kind":"goods","tier":3,"stack":10,"pays":26},
    "shrimpPaste": {"kind":"goods","tier":3,"stack":10,"pays":28},
    "driedChili": {"kind":"goods","tier":3,"stack":20,"pays":8},
    "riceNoodle": {"kind":"goods","tier":3,"stack":10,"pays":18},
    "bananaLeaf": {"kind":"goods","tier":3,"stack":20,"pays":2},
    "toastedRice": {"kind":"goods","tier":3,"stack":10,"pays":10},
    "greenCurry": {"kind":"dish","tier":3,"stack":5,"pays":60},
    "khanomJeen": {"kind":"dish","tier":3,"stack":5,"pays":70},
    "hoMok": {"kind":"dish","tier":3,"stack":5,"pays":56},
    "mangoStickyRice": {"kind":"dish","tier":3,"stack":5,"pays":50},
    "bananaInCoconut": {"kind":"dish","tier":3,"stack":5,"pays":34},
    "taroPudding": {"kind":"dish","tier":3,"stack":5,"pays":44},
    "steamedCroaker": {"kind":"dish","tier":3,"stack":5,"pays":56},
    "gingerFish": {"kind":"dish","tier":3,"stack":5,"pays":54},
    "turmericFish": {"kind":"dish","tier":3,"stack":5,"pays":50},
    "jungleCurry": {"kind":"dish","tier":3,"stack":5,"pays":66},
    "megaLaab": {"kind":"dish","tier":3,"stack":20,"pays":90},
    "watermelonSlices": {"kind":"dish","tier":3,"stack":10,"pays":20},
    "khantoke": {"kind":"dish","tier":3,"stack":20,"pays":120},
    "naamPrik": {"kind":"dish","tier":3,"stack":5,"pays":36},
    "ramen": {"kind":"dish","tier":3,"stack":5,"pays":44},
    "unadon": {"kind":"dish","tier":3,"stack":5,"pays":48},
    "tteokbokki": {"kind":"dish","tier":3,"stack":5,"pays":36},
    "chowMein": {"kind":"dish","tier":3,"stack":5,"pays":40},
    "mapoTofu": {"kind":"dish","tier":3,"stack":5,"pays":40},
    "pizza": {"kind":"dish","tier":3,"stack":5,"pays":46},
    "risotto": {"kind":"dish","tier":3,"stack":5,"pays":40},
    "lasagna": {"kind":"dish","tier":3,"stack":5,"pays":50},
    "fishCurry": {"kind":"dish","tier":3,"stack":5,"pays":46},
    "naan": {"kind":"dish","tier":3,"stack":5,"pays":26},
    "biryani": {"kind":"dish","tier":3,"stack":5,"pays":46},
    "lassi": {"kind":"dish","tier":3,"stack":5,"pays":24},
    "scrollGreenCurry": {"kind":"scroll","tier":3,"stack":1,"pays":0},
    "scrollHoMok": {"kind":"scroll","tier":3,"stack":1,"pays":0},
    "scrollKhanomJeen": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollMangoStickyRice": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollBananaInCoconut": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollTaroPudding": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollSteamedCroaker": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollGingerFish": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollTurmericFish": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollJungleCurry": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollMegaLaab": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollWatermelonSlices": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollKhantoke": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollNaamPrik": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollRamen": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollUnadon": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollTteokbokki": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollChowMein": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollMapoTofu": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollPizza": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollRisotto": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollLasagna": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollFishCurry": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollNaan": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollBiryani": {"kind":"scroll","tier":3,"stack":1,"pays":35},
    "scrollLassi": {"kind":"scroll","tier":3,"stack":1,"pays":35}
  }$town$::jsonb),
  ('goods', $town${
    "rod": {"price":60,"stock":6,"each":1},
    "hoe": {"price":50,"stock":6,"each":1},
    "can": {"price":40,"stock":6,"each":1},
    "pot": {"price":80,"stock":4,"each":1},
    "pan": {"price":70,"stock":4,"each":1},
    "grill": {"price":60,"stock":4,"each":1},
    "worm": {"price":2,"stock":120,"each":10},
    "dough": {"price":3,"stock":80,"each":10},
    "rice": {"price":3,"stock":100,"each":10},
    "salt": {"price":2,"stock":100,"each":10},
    "riceBox": {"price":6,"stock":40,"each":3},
    "seedKangkong": {"price":4,"stock":100,"each":8},
    "seedScallion": {"price":5,"stock":100,"each":8},
    "seedCabbage": {"price":8,"stock":60,"each":6},
    "seedCarrot": {"price":8,"stock":60,"each":6},
    "seedChili": {"price":10,"stock":40,"each":4},
    "seedPumpkin": {"price":25,"stock":20,"each":2},
    "scrollFriedMinnow": {"price":40,"stock":3,"each":1},
    "scrollGrilledFish": {"price":40,"stock":3,"each":1},
    "bowl": {"price":5,"stock":60,"each":5},
    "scrubber": {"price":4,"stock":60,"each":5},
    "ash": {"price":2,"stock":100,"each":10},
    "bucket": {"price":20,"stock":30,"each":4},
    "bucketIron": {"price":70,"stock":6,"each":1},
    "brush": {"price":60,"stock":6,"each":1},
    "soap": {"price":8,"stock":60,"each":10},
    "apron": {"price":120,"stock":4,"each":1},
    "seedDaikon": {"price":10,"stock":40,"each":4},
    "seedCorn": {"price":12,"stock":40,"each":4},
    "seedTomato": {"price":14,"stock":40,"each":4},
    "seedBasil": {"price":8,"stock":40,"each":4},
    "seedSweetPotato": {"price":14,"stock":40,"each":4},
    "seedGarlic": {"price":10,"stock":40,"each":4},
    "rodTeak": {"price":240,"stock":3,"each":1},
    "floatQuill": {"price":90,"stock":4,"each":1},
    "hookSteel": {"price":90,"stock":4,"each":1},
    "lineBraid": {"price":90,"stock":4,"each":1},
    "netSmall": {"price":110,"stock":4,"each":1},
    "hoeIron": {"price":180,"stock":4,"each":1},
    "canCopper": {"price":150,"stock":4,"each":1},
    "sickle": {"price":120,"stock":4,"each":1},
    "krabung": {"price":150,"stock":4,"each":1},
    "mortar": {"price":130,"stock":4,"each":1},
    "steamer": {"price":160,"stock":4,"each":1},
    "cleaver": {"price":130,"stock":4,"each":1},
    "jar": {"price":110,"stock":6,"each":2},
    "wok": {"price":190,"stock":4,"each":1},
    "cricket": {"price":4,"stock":80,"each":10},
    "branBait": {"price":4,"stock":80,"each":10},
    "shrimpLive": {"price":6,"stock":60,"each":10},
    "sugar": {"price":6,"stock":80,"each":10},
    "oil": {"price":6,"stock":80,"each":10},
    "tamarind": {"price":5,"stock":80,"each":10},
    "egg": {"price":6,"stock":60,"each":10},
    "manure": {"price":8,"stock":60,"each":10},
    "flour": {"price":7,"stock":80,"each":10},
    "seaweed": {"price":8,"stock":60,"each":10},
    "tofu": {"price":7,"stock":60,"each":10},
    "rollingPin": {"price":90,"stock":4,"each":1},
    "sushiMat": {"price":100,"stock":4,"each":1},
    "stoneBowl": {"price":140,"stock":4,"each":1},
    "seedEggplant": {"price":18,"stock":40,"each":4},
    "seedCucumber": {"price":16,"stock":40,"each":4},
    "seedLongBean": {"price":16,"stock":40,"each":4},
    "seedLemongrass": {"price":20,"stock":40,"each":4},
    "seedGalangal": {"price":26,"stock":30,"each":4},
    "seedLime": {"price":70,"stock":12,"each":2},
    "seedPapaya": {"price":32,"stock":20,"each":2},
    "scrollSomTam": {"price":90,"stock":3,"each":1},
    "scrollOmelette": {"price":60,"stock":3,"each":1},
    "rodMaster": {"price":600,"stock":2,"each":1},
    "floatBell": {"price":220,"stock":3,"each":1},
    "hookTwin": {"price":220,"stock":3,"each":1},
    "lineSilk": {"price":220,"stock":3,"each":1},
    "netLong": {"price":260,"stock":3,"each":1},
    "hoeSteel": {"price":420,"stock":3,"each":1},
    "canBrass": {"price":360,"stock":3,"each":1},
    "shears": {"price":280,"stock":3,"each":1},
    "yoke": {"price":300,"stock":3,"each":1},
    "potBrass": {"price":460,"stock":3,"each":1},
    "stoveBig": {"price":380,"stock":3,"each":1},
    "panBrass": {"price":440,"stock":3,"each":1},
    "steamerBamboo": {"price":330,"stock":3,"each":1},
    "hotpot": {"price":520,"stock":2,"each":1},
    "ladle": {"price":50,"stock":10,"each":1},
    "tok": {"price":150,"stock":6,"each":1},
    "antEggs": {"price":14,"stock":50,"each":10},
    "lure": {"price":70,"stock":10,"each":2},
    "fermentedBait": {"price":12,"stock":50,"each":10},
    "stickyRice": {"price":7,"stock":80,"each":10},
    "soy": {"price":12,"stock":60,"each":10},
    "pepper": {"price":14,"stock":60,"each":10},
    "bananaLeaf": {"price":5,"stock":80,"each":10},
    "cheese": {"price":16,"stock":50,"each":10},
    "milk": {"price":9,"stock":60,"each":10},
    "oven": {"price":480,"stock":2,"each":1},
    "seedMango": {"price":95,"stock":10,"each":2},
    "seedBanana": {"price":60,"stock":12,"each":2},
    "seedCoconut": {"price":110,"stock":8,"each":2},
    "seedGinger": {"price":38,"stock":30,"each":4},
    "seedTurmeric": {"price":38,"stock":30,"each":4},
    "seedTaro": {"price":42,"stock":30,"each":4},
    "seedWatermelon": {"price":46,"stock":20,"each":2},
    "scrollGreenCurry": {"price":160,"stock":2,"each":1},
    "scrollHoMok": {"price":160,"stock":2,"each":1}
  }$town$::jsonb),
  ('shelf', $town${
    "basic": ["rod","hoe","can","pot","pan","grill","worm","dough","rice","salt","riceBox","seedKangkong","seedScallion","seedCabbage","seedCarrot","seedChili","seedPumpkin","scrollFriedMinnow","scrollGrilledFish","bowl","scrubber","ash","bucket"],
    "unlocks": ["seedGarlic","seedBasil","seedTomato","seedCorn","seedDaikon","seedSweetPotato","cricket","seedCucumber","oil","egg","scrollOmelette","flour","mortar","seedLongBean","sugar","rollingPin","seedEggplant","branBait","wok","seaweed","seedLemongrass","jar","sushiMat","seedGalangal","shrimpLive","steamer","tofu","seedLime","cleaver","stoneBowl","seedPapaya","scrollSomTam","tamarind","manure","floatQuill","hookSteel","lineBraid","netSmall","rodTeak","hoeIron","canCopper","sickle","krabung","bucketIron","brush","soap","apron","antEggs","seedGinger","soy","stickyRice","seedBanana","bananaLeaf","pepper","milk","seedTurmeric","seedTaro","fermentedBait","cheese","seedWatermelon","steamerBamboo","oven","seedCoconut","seedMango","lure","potBrass","panBrass","hotpot","stoveBig","ladle","tok","scrollGreenCurry","scrollHoMok","floatBell","hookTwin","lineSilk","netLong","rodMaster","hoeSteel","canBrass","shears","yoke"]
  }$town$::jsonb),
  ('order', $town${
    "n": {"fish":[4,8],"crop":[4,8],"made":[2,4]},
    "asks": {"fish":[["minnow",0],["barb",0],["tilapia",0],["perch",0],["catfish",0],["gourami",7],["crab",18],["snail",18]],"crop":[["kangkong",0],["scallion",0],["cabbage",0],["carrot",0],["daikon",5],["corn",4],["chili",0],["basil",2],["cucumber",8],["longBean",14]],"made":[["friedMinnow",0],["grilledFish",0],["grilledCorn",4],["sourCurry",5],["friedGourami",19],["omelette",10],["friedRice",19],["sushi",29],["ramen",50],["bibimbap",30],["tteokbokki",51],["kimbap",23],["pajeon",12],["chowMein",50],["springRoll",19],["congee",10],["fishSauce",0],["compost",0],["growFert",0],["driedFish",7],["saltedFish",22],["pickle",22],["rope",7],["noodle",16],["fermentedFish",48],["shrimpPaste",48],["driedChili",48],["riceNoodle",48],["toastedRice",48]]}
  }$town$::jsonb),
  ('hints', $town${
    "price": {"1":15,"2":40,"3":90},
    "ids": [["friedMinnow",0],["grilledFish",0],["grilledCorn",4],["roastSweetPotato",6],["stirKangkong",1],["basilCatfish",2],["tomYum",3],["sourCurry",5],["friedPerch",1],["fishCake",2],["spicyEel",2],["grilledPrawn",0],["steamedGoby",0],["pumpkinSoup",0],["shabu",5],["fishSauce",0],["compost",0],["growFert",0],["guardFert",1],["pestCure",2],["basket",0],["somTam",31],["grilledEggplant",17],["tomKha",28],["friedGourami",19],["crabCurry",24],["steamedSheatfish",28],["friedFrog",19],["laab",29],["omelette",10],["snailCurry",24],["candiedPumpkin",15],["friedRice",19],["sushi",29],["tempura",19],["okonomiyaki",12],["kimchi",22],["bibimbap",30],["kimbap",23],["pajeon",12],["harGow",26],["springRoll",19],["congee",10],["spaghetti",16],["minestrone",16],["samosa",19],["driedFish",0],["saltedFish",22],["curryPaste",24],["pickle",22],["charcoal",7],["rope",0],["krabung",0],["soap",9],["noodle",16],["greenCurry",63],["khanomJeen",63],["hoMok",63],["mangoStickyRice",64],["bananaInCoconut",63],["taroPudding",67],["steamedCroaker",50],["gingerFish",58],["turmericFish",56],["jungleCurry",66],["megaLaab",48],["watermelonSlices",60],["khantoke",68],["naamPrik",28],["ramen",50],["unadon",50],["tteokbokki",51],["chowMein",50],["mapoTofu",50],["pizza",62],["risotto",59],["lasagna",62],["fishCurry",63],["naan",62],["biryani",56],["lassi",64],["coconutMilk",63],["fermentedFish",22],["shrimpPaste",25],["driedChili",0],["riceNoodle",12],["toastedRice",19],["yoke",7]]
  }$town$::jsonb),
  ('dishes', $town${
    "riceBox": {"stamina":15,"buff":null,"recipe":null},
    "oddDish": {"stamina":6,"buff":null,"recipe":null},
    "friedMinnow": {"stamina":20,"buff":"keen","recipe":{"needs":[["minnow",3],["salt",1]],"in":["pan"],"serves":2,"cooks":1}},
    "grilledFish": {"stamina":25,"buff":"calm","recipe":{"needs":[["tilapia",1],["salt",2]],"in":["grill"],"serves":2,"cooks":1}},
    "grilledCorn": {"stamina":15,"buff":null,"recipe":{"needs":[["corn",2]],"in":["grill"],"serves":2,"cooks":1}},
    "roastSweetPotato": {"stamina":18,"buff":null,"recipe":{"needs":[["sweetPotato",2]],"in":["grill"],"serves":2,"cooks":1}},
    "stirKangkong": {"stamina":22,"buff":"green","recipe":{"needs":[["kangkong",3],["chili",1],["garlic",1]],"in":["pan"],"serves":3,"cooks":1}},
    "basilCatfish": {"stamina":35,"buff":"hearty","recipe":{"needs":[["catfish",1],["basil",2],["chili",1],["garlic",1],["rice",2]],"in":["pan"],"serves":3,"cooks":1}},
    "tomYum": {"stamina":40,"buff":"hearty","recipe":{"needs":[["snakehead",1],["tomato",2],["chili",2],["scallion",1]],"in":["pot"],"serves":4,"cooks":1}},
    "sourCurry": {"stamina":32,"buff":"calm","recipe":{"needs":[["barb",2],["daikon",1],["cabbage",1],["chili",1]],"in":["pot"],"serves":4,"cooks":1}},
    "friedPerch": {"stamina":28,"buff":"keen","recipe":{"needs":[["perch",2],["garlic",2],["salt",1]],"in":["pan"],"serves":2,"cooks":1}},
    "fishCake": {"stamina":38,"buff":"calm","recipe":{"needs":[["featherback",1],["basil",1],["chili",1],["salt",1]],"in":["pan"],"serves":4,"cooks":1}},
    "spicyEel": {"stamina":40,"buff":"hearty","recipe":{"needs":[["eel",1],["basil",2],["chili",2],["garlic",1]],"in":["pan"],"serves":3,"cooks":1}},
    "grilledPrawn": {"stamina":30,"buff":"lucky","recipe":{"needs":[["prawn",2],["salt",1]],"in":["grill"],"serves":2,"cooks":1}},
    "steamedGoby": {"stamina":45,"buff":"lucky","recipe":{"needs":[["goby",1],["scallion",2],["fishSauce",1]],"in":["pot"],"serves":3,"cooks":1}},
    "pumpkinSoup": {"stamina":28,"buff":"green","recipe":{"needs":[["pumpkin",1],["scallion",1],["salt",1]],"in":["pot"],"serves":5,"cooks":1}},
    "shabu": {"stamina":50,"buff":"lucky","recipe":{"needs":[["cabbage",1],["carrot",2],["daikon",1],["corn",1],["scallion",2],["prawn",2],["pangasius",1]],"in":["pot"],"serves":10,"cooks":3}},
    "somTam": {"stamina":30,"buff":"keen","recipe":{"needs":[["papaya",1],["lime",1],["chili",2],["longBean",1],["tomato",1],["sugar",1]],"in":["mortar"],"serves":3,"cooks":1}},
    "grilledEggplant": {"stamina":22,"buff":"calm","recipe":{"needs":[["eggplant",2],["fishSauce",1]],"in":["grill"],"serves":2,"cooks":1}},
    "tomKha": {"stamina":42,"buff":"hearty","recipe":{"needs":[["sheatfish",1],["galangal",1],["lemongrass",1],["lime",1],["chili",1]],"in":["pot"],"serves":4,"cooks":1}},
    "friedGourami": {"stamina":26,"buff":null,"recipe":{"needs":[["gourami",2],["oil",1],["salt",1]],"in":["wok"],"serves":2,"cooks":1}},
    "crabCurry": {"stamina":46,"buff":"lucky","recipe":{"needs":[["crab",3],["curryPaste",1],["longBean",1],["eggplant",1]],"in":["mortar","pot"],"serves":4,"cooks":2}},
    "steamedSheatfish": {"stamina":40,"buff":"calm","recipe":{"needs":[["sheatfish",1],["lime",2],["chili",1],["garlic",1]],"in":["steamer"],"serves":3,"cooks":1}},
    "friedFrog": {"stamina":36,"buff":"keen","recipe":{"needs":[["frog",2],["garlic",2],["oil",1]],"in":["wok"],"serves":2,"cooks":1}},
    "laab": {"stamina":44,"buff":"hearty","recipe":{"needs":[["bagrid",1],["lime",1],["chili",1],["scallion",1],["rice",1]],"in":["cleaver","mortar"],"serves":4,"cooks":2}},
    "omelette": {"stamina":20,"buff":null,"recipe":{"needs":[["egg",2],["oil",1]],"in":["pan"],"serves":2,"cooks":1}},
    "snailCurry": {"stamina":40,"buff":"green","recipe":{"needs":[["snail",6],["curryPaste",1],["lemongrass",1]],"in":["mortar","pot"],"serves":4,"cooks":2}},
    "candiedPumpkin": {"stamina":28,"buff":"green","recipe":{"needs":[["pumpkin",1],["sugar",2]],"in":["pot"],"serves":5,"cooks":1}},
    "friedRice": {"stamina":34,"buff":null,"recipe":{"needs":[["rice",3],["egg",1],["scallion",1],["oil",1]],"in":["wok"],"serves":3,"cooks":1}},
    "greenCurry": {"stamina":48,"buff":"calm","recipe":{"needs":[["featherback",1],["curryPaste",1],["coconutMilk",1],["eggplant",2],["basil",1]],"in":["mortar","pot"],"serves":5,"cooks":2}},
    "khanomJeen": {"stamina":50,"buff":"hearty","recipe":{"needs":[["riceNoodle",3],["croaker",1],["curryPaste",1],["coconutMilk",1],["longBean",1]],"in":["mortar","pot","steamer"],"serves":6,"cooks":3}},
    "hoMok": {"stamina":48,"buff":"lucky","recipe":{"needs":[["blackEar",1],["curryPaste",1],["coconutMilk",1],["bananaLeaf",2],["basil",1]],"in":["mortar","steamerBamboo"],"serves":4,"cooks":2}},
    "mangoStickyRice": {"stamina":44,"buff":"green","recipe":{"needs":[["mango",2],["stickyRice",2],["coconutMilk",1],["sugar",1]],"in":["steamerBamboo","pot"],"serves":4,"cooks":2}},
    "bananaInCoconut": {"stamina":32,"buff":"calm","recipe":{"needs":[["banana",3],["coconutMilk",1],["sugar",1]],"in":["pot"],"serves":4,"cooks":1}},
    "taroPudding": {"stamina":40,"buff":"keen","recipe":{"needs":[["taro",1],["flour",1],["coconutMilk",1],["sugar",1]],"in":["panBrass","pot"],"serves":6,"cooks":2}},
    "steamedCroaker": {"stamina":46,"buff":"keen","recipe":{"needs":[["croaker",1],["soy",1],["ginger",1],["scallion",1]],"in":["steamer"],"serves":3,"cooks":1}},
    "gingerFish": {"stamina":45,"buff":"hearty","recipe":{"needs":[["blackEar",1],["ginger",2],["soy",1],["oil",1]],"in":["wok"],"serves":4,"cooks":1}},
    "turmericFish": {"stamina":44,"buff":"calm","recipe":{"needs":[["spinyEel",2],["turmeric",1],["garlic",2],["oil",1]],"in":["wok"],"serves":3,"cooks":1}},
    "jungleCurry": {"stamina":50,"buff":"lucky","recipe":{"needs":[["giantSnakehead",1],["curryPaste",1],["galangal",1],["lemongrass",1],["eggplant",1],["longBean",1]],"in":["mortar","potBrass"],"serves":6,"cooks":2}},
    "megaLaab": {"stamina":50,"buff":"hearty","recipe":{"needs":[["megaCatfish",1],["toastedRice",1],["lime",3],["chili",3],["scallion",2]],"in":["cleaver","mortar","wok"],"serves":20,"cooks":3}},
    "watermelonSlices": {"stamina":24,"buff":null,"recipe":{"needs":[["watermelon",1]],"in":["cleaver"],"serves":6,"cooks":1}},
    "khantoke": {"stamina":50,"buff":"lucky","recipe":{"needs":[["stickyRice",3],["goldenCarp",1],["curryPaste",1],["coconutMilk",1],["cucumber",2],["longBean",2],["pepper",1]],"in":["hotpot","steamerBamboo","wok","mortar"],"serves":20,"cooks":4}},
    "naamPrik": {"stamina":38,"buff":"green","recipe":{"needs":[["fermentedFish",1],["chili",3],["garlic",1],["lime",1],["cucumber",1]],"in":["mortar"],"serves":4,"cooks":1}},
    "sushi": {"stamina":38,"buff":"keen","recipe":{"needs":[["tilapia",1],["rice",2],["sugar",1],["seaweed",1]],"in":["cleaver","sushiMat"],"serves":4,"cooks":2}},
    "ramen": {"stamina":46,"buff":"hearty","recipe":{"needs":[["noodle",2],["egg",1],["scallion",1],["soy",1],["driedFish",1]],"in":["pot"],"serves":3,"cooks":1}},
    "tempura": {"stamina":34,"buff":"lucky","recipe":{"needs":[["prawn",2],["flour",1],["oil",1],["egg",1]],"in":["wok"],"serves":2,"cooks":1}},
    "unadon": {"stamina":48,"buff":"hearty","recipe":{"needs":[["eel",1],["rice",2],["sugar",1],["soy",1]],"in":["grill"],"serves":2,"cooks":1}},
    "okonomiyaki": {"stamina":36,"buff":"green","recipe":{"needs":[["flour",1],["egg",1],["cabbage",1],["scallion",1],["prawn",1]],"in":["pan"],"serves":3,"cooks":1}},
    "kimchi": {"stamina":20,"buff":"hearty","recipe":{"needs":[["cabbage",2],["chili",2],["garlic",1],["fishSauce",1]],"in":["jar"],"serves":4,"cooks":1}},
    "bibimbap": {"stamina":44,"buff":"hearty","recipe":{"needs":[["rice",2],["egg",1],["carrot",1],["cucumber",1],["kangkong",1],["chili",1]],"in":["wok","stoneBowl"],"serves":4,"cooks":2}},
    "tteokbokki": {"stamina":36,"buff":"keen","recipe":{"needs":[["stickyRice",2],["chili",2],["scallion",1],["sugar",1]],"in":["mortar","pan"],"serves":3,"cooks":2}},
    "kimbap": {"stamina":32,"buff":"calm","recipe":{"needs":[["rice",2],["seaweed",1],["carrot",1],["cucumber",1],["egg",1]],"in":["sushiMat"],"serves":3,"cooks":1}},
    "pajeon": {"stamina":28,"buff":null,"recipe":{"needs":[["flour",1],["egg",1],["oil",1],["scallion",3]],"in":["pan"],"serves":2,"cooks":1}},
    "harGow": {"stamina":34,"buff":"lucky","recipe":{"needs":[["flour",2],["scallion",1],["prawn",2]],"in":["rollingPin","steamer"],"serves":4,"cooks":2}},
    "chowMein": {"stamina":40,"buff":"keen","recipe":{"needs":[["noodle",2],["cabbage",1],["carrot",1],["oil",1],["soy",1]],"in":["wok"],"serves":3,"cooks":1}},
    "springRoll": {"stamina":26,"buff":null,"recipe":{"needs":[["flour",1],["cabbage",1],["oil",1],["carrot",1]],"in":["rollingPin","wok"],"serves":4,"cooks":2}},
    "congee": {"stamina":30,"buff":"calm","recipe":{"needs":[["rice",2],["egg",1],["scallion",1],["perch",1]],"in":["pot"],"serves":4,"cooks":1}},
    "mapoTofu": {"stamina":40,"buff":"hearty","recipe":{"needs":[["chili",2],["garlic",1],["scallion",1],["soy",1],["tofu",2]],"in":["wok"],"serves":3,"cooks":1}},
    "pizza": {"stamina":46,"buff":"lucky","recipe":{"needs":[["flour",2],["tomato",2],["basil",1],["cheese",1]],"in":["rollingPin","oven"],"serves":6,"cooks":2}},
    "spaghetti": {"stamina":40,"buff":"keen","recipe":{"needs":[["noodle",2],["tomato",2],["oil",1],["prawn",1],["garlic",1]],"in":["pot","pan"],"serves":3,"cooks":2}},
    "risotto": {"stamina":38,"buff":"calm","recipe":{"needs":[["rice",2],["pumpkin",1],["garlic",1],["cheese",1]],"in":["pot"],"serves":4,"cooks":1}},
    "lasagna": {"stamina":48,"buff":"hearty","recipe":{"needs":[["noodle",2],["tomato",2],["cheese",2],["eggplant",1]],"in":["oven","pot"],"serves":6,"cooks":2}},
    "minestrone": {"stamina":30,"buff":"green","recipe":{"needs":[["tomato",2],["carrot",1],["cabbage",1],["longBean",1],["noodle",1]],"in":["pot"],"serves":5,"cooks":1}},
    "fishCurry": {"stamina":46,"buff":"hearty","recipe":{"needs":[["catfish",1],["chili",2],["ginger",1],["turmeric",1],["coconutMilk",1]],"in":["mortar","pot"],"serves":4,"cooks":2}},
    "naan": {"stamina":26,"buff":null,"recipe":{"needs":[["flour",2],["garlic",1],["milk",1]],"in":["rollingPin","oven"],"serves":4,"cooks":2}},
    "biryani": {"stamina":44,"buff":"calm","recipe":{"needs":[["rice",3],["turmeric",1],["milk",1],["pepper",1],["pangasius",1]],"in":["pot"],"serves":5,"cooks":1}},
    "samosa": {"stamina":28,"buff":"green","recipe":{"needs":[["flour",1],["chili",1],["oil",1],["sweetPotato",1]],"in":["rollingPin","wok"],"serves":4,"cooks":2}},
    "lassi": {"stamina":24,"buff":"lucky","recipe":{"needs":[["mango",1],["sugar",1],["milk",1]],"in":["mortar"],"serves":3,"cooks":1}}
  }$town$::jsonb),
  ('scrolls', $town${
    "scrollFriedMinnow": "friedMinnow",
    "scrollGrilledFish": "grilledFish",
    "scrollGrilledCorn": "grilledCorn",
    "scrollRoastSweetPotato": "roastSweetPotato",
    "scrollStirKangkong": "stirKangkong",
    "scrollBasilCatfish": "basilCatfish",
    "scrollTomYum": "tomYum",
    "scrollSourCurry": "sourCurry",
    "scrollFriedPerch": "friedPerch",
    "scrollFishCake": "fishCake",
    "scrollSpicyEel": "spicyEel",
    "scrollGrilledPrawn": "grilledPrawn",
    "scrollSteamedGoby": "steamedGoby",
    "scrollPumpkinSoup": "pumpkinSoup",
    "scrollShabu": "shabu",
    "scrollSomTam": "somTam",
    "scrollGrilledEggplant": "grilledEggplant",
    "scrollTomKha": "tomKha",
    "scrollFriedGourami": "friedGourami",
    "scrollCrabCurry": "crabCurry",
    "scrollSteamedSheatfish": "steamedSheatfish",
    "scrollFriedFrog": "friedFrog",
    "scrollLaab": "laab",
    "scrollOmelette": "omelette",
    "scrollSnailCurry": "snailCurry",
    "scrollCandiedPumpkin": "candiedPumpkin",
    "scrollFriedRice": "friedRice",
    "scrollSushi": "sushi",
    "scrollTempura": "tempura",
    "scrollOkonomiyaki": "okonomiyaki",
    "scrollKimchi": "kimchi",
    "scrollBibimbap": "bibimbap",
    "scrollKimbap": "kimbap",
    "scrollPajeon": "pajeon",
    "scrollHarGow": "harGow",
    "scrollSpringRoll": "springRoll",
    "scrollCongee": "congee",
    "scrollSpaghetti": "spaghetti",
    "scrollMinestrone": "minestrone",
    "scrollSamosa": "samosa",
    "scrollGreenCurry": "greenCurry",
    "scrollKhanomJeen": "khanomJeen",
    "scrollHoMok": "hoMok",
    "scrollMangoStickyRice": "mangoStickyRice",
    "scrollBananaInCoconut": "bananaInCoconut",
    "scrollTaroPudding": "taroPudding",
    "scrollSteamedCroaker": "steamedCroaker",
    "scrollGingerFish": "gingerFish",
    "scrollTurmericFish": "turmericFish",
    "scrollJungleCurry": "jungleCurry",
    "scrollMegaLaab": "megaLaab",
    "scrollWatermelonSlices": "watermelonSlices",
    "scrollKhantoke": "khantoke",
    "scrollNaamPrik": "naamPrik",
    "scrollRamen": "ramen",
    "scrollUnadon": "unadon",
    "scrollTteokbokki": "tteokbokki",
    "scrollChowMein": "chowMein",
    "scrollMapoTofu": "mapoTofu",
    "scrollPizza": "pizza",
    "scrollRisotto": "risotto",
    "scrollLasagna": "lasagna",
    "scrollFishCurry": "fishCurry",
    "scrollNaan": "naan",
    "scrollBiryani": "biryani",
    "scrollLassi": "lassi"
  }$town$::jsonb)
  on conflict (key) do update set data = excluded.data, updated_at = now();
-- </catalog:v109>

notify pgrst, 'reload schema';

-- ─── Before running it ───────────────────────────────────────────────────
--
-- Has a number been changed by hand? v106 to v108 wrote every row within a
-- minute or two of each other; a row with a later time has been touched since.
--
--   select key, updated_at from public.town_catalog order by updated_at desc, key;
--
-- Is anybody's purse in use, or anything on the shelf opened?
--
--   select (select count(*) from public.town_purses where coins > 0 or doc <> town.fresh()) as purses_in_use,
--          (select doc->>'unlocked' from public.town_things where key = 'village') as opened;
--   -- 0 | 0
--
-- ─── What it should say afterwards ───────────────────────────────────────
--
--   select key, case jsonb_typeof(data) when 'object' then (select count(*) from jsonb_object_keys(data)) end as n,
--          updated_at > now() - interval '1 hour' as written
--     from public.town_catalog order by key;
--   -- carries | 3   | f
--   -- dishes  | 68  | t
--   -- fish    | 32  | f
--   -- fishing | 15  | f
--   -- flotsam | 6   | f
--   -- goods   | 105 | t
--   -- hints   | 2   | t
--   -- items   | 317 | t
--   -- order   | 2   | t
--   -- rules   | 3   | f
--   -- scrolls | 66  | t
--   -- shelf   | 2   | t
--   -- stamina | 7   | f
--   -- (`written` is true for an hour after it runs)
--
--   select jsonb_array_length(data->'basic') as basic, jsonb_array_length(data->'unlocks') as unlocks
--     from public.town_catalog where key = 'shelf';
--   -- 23 | 82
--
--   select jsonb_array_length(data->'ids') as hints from public.town_catalog where key = 'hints';
--   -- 88
--
--   select (data->'pot'->>'pays')::int as a_pot_fetches, data->'flour'->>'tier' as flour_tier,
--          data ? 'sushi' as sushi, data ? 'scrollTomYum' as a_found_scroll, data ? 'oven' as an_oven
--     from public.town_catalog where key = 'items';
--   -- 0 | 2 | t | t | t
