"use client";
import { carriedBag } from "@/lib/town/passive-equipment";
import {useEffect,useState} from "react";
import type {FishSfx} from "@/lib/town/sfx";
import type {Keeper} from "@/lib/town/keeper";
import {ITEMS,byOf,type ItemId} from "@/lib/town/items";
import {PREP_MAKES} from "@/lib/town/preparation-items";
import {atPreparation,preparationReady,PREPARATION,type PrepAnswers,type PrepId,type PrepRun} from "@/lib/town/preparation";
import {CAMPS,campSiteAt} from "@/lib/town/camps";
import {held} from "@/lib/town/trade";
import {dayOf,levelOf} from "@/lib/town/stamina";
import {WISH} from "@/lib/town/fountain";
import TownFoot from "./TownFoot";
import TownIcon,{ICON_ATLAS,type IconName} from "./TownIcon";
import type {FarmDraw} from "./TownFarm";
import TownNotebook from "./TownNotebook";
import styles from "./TownAdventure.module.css";

const methods=[["หั่นเป็นชิ้น","Cut"],["บดหรือตำ","Grind"],["คลุกหรือตี","Fold or whisk"]],heat=[["อ่อน / พัก","Low / rest"],["กลาง / เคี่ยว","Medium / simmer"],["แรง / คั่ว","High / toast"]],finish=[["สีอ่อน · เสียงเงียบ","Pale · quiet"],["สีทอง · เสียงกรอบ","Golden · crackling"],["ใสข้น · เดือดเบา","Clear and thick · bubbling"]];
const refuses:Record<string,[string,string]>={none:["วัตถุดิบหรือการทดลองยังไม่พร้อม","The supplies or experiment are not ready."],tool:["ยังขาดเครื่องมือ","A tool is missing."],full:["กระเป๋าเต็ม","Your bag is full."],far:["กลับไปจุดที่เริ่มทำ","Return to the place where you began."],spent:["ค่ายนี้หรือโควตาวันนี้ใช้ไปแล้ว","The camp or today's allowance is used up."],had:["คำขอนี้ทำไปแล้ว","This request has already been handled."]};
export default function TownFieldwork({keeper,tile,busy,th,far,register,sfx}:{keeper:Keeper;tile:[number,number]|null;busy:boolean;th:boolean;far:boolean;register:(draw:FarmDraw|null)=>void;sfx:FishSfx|null}){
 const [open,setOpen]=useState(false),[pending,setPending]=useState(false),[note,setNote]=useState("");
 const [run,setRun]=useState<PrepRun|null>(null),[answers,setAnswers]=useState<PrepAnswers>({method:0,heat:0,finish:0});
 const [,redraw]=useState(0),[,setTick]=useState(0);
 const p=keeper.purse(),station=!!tile&&atPreparation(tile),site=far&&tile?campSiteAt(tile):-1;
 const active=!busy&&(station||site>=0),lang=th?0:1;
 useEffect(()=>keeper.watch(()=>redraw(n=>n+1)),[keeper]);
 useEffect(()=>{if(site<0||busy)return;const refresh=()=>{if(!document.hidden)void keeper.campsLook();};refresh();const timer=setInterval(refresh,15000);document.addEventListener("visibilitychange",refresh);return()=>{clearInterval(timer);document.removeEventListener("visibilitychange",refresh);};},[keeper,site,busy]);
 useEffect(()=>{if(!run)return;const timer=setInterval(()=>setTick(n=>n+1),500);return()=>clearInterval(timer);},[run]);
 useEffect(()=>{register(({ctx,things,project,onScreen,img,s,self})=>{
   if(!img?.complete||!img.naturalWidth)return;
   const camps=keeper.camps().filter(c=>c.until>keeper.now());
   for(const c of camps){const at=project({x:c.x+0.5,y:c.y+0.5});if(!onScreen(at))continue;
    things.push({depth:at.y,draw:()=>{const name:IconName="fieldCamp",[x,y,w,h]=ICON_ATLAS.icons[name],k=45*s/Math.max(w,h);ctx.save();ctx.imageSmoothingEnabled=false;ctx.drawImage(img,x,y,w,h,Math.round(at.x-w*k/2),Math.round(at.y-h*k),w*k,h*k);if(c.wide){ctx.fillStyle="#8b3b31";ctx.fillRect(at.x+12*s,at.y-40*s,12*s,7*s);ctx.fillStyle="#725533";ctx.fillRect(at.x+12*s,at.y-40*s,2*s,40*s);}if(c.lit){ctx.fillStyle="#ffdd88";ctx.fillRect(at.x+8*s,at.y-10*s,3*s,3*s);}ctx.restore();}});
   }
   for(const [index,where] of CAMPS.sites.entries()){
    if(camps.some(c=>c.site===index)||!self||Math.max(Math.abs(where[0]-self.x),Math.abs(where[1]-self.y))>4)continue;
    const at=project({x:where[0]+0.5,y:where[1]+0.5});if(!onScreen(at))continue;
    things.push({depth:at.y,draw:()=>{ctx.save();ctx.fillStyle="#ded4a0";ctx.fillRect(at.x-7*s,at.y-2*s,14*s,3*s);ctx.restore();}});
   }
 });return()=>register(null);},[keeper,register]);
 const name=(id:ItemId)=>ITEMS[id].name[th?"th":"en"],say=(why:string)=>setNote(refuses[why]?.[lang]??(th?"ยังทำไม่ได้":"Not ready."));
 async function begin(recipe:PrepId){if(!tile||pending)return;setPending(true);setNote("");try{const d=await keeper.preparationBegin(recipe,tile,crypto.randomUUID());if(d.ok){setRun(d.run);setAnswers({method:0,heat:d.run.seed%3,finish:0});}else say(d.why);}finally{setPending(false);}}
 async function end(){if(!run||!tile||pending)return;setPending(true);try{const d=await keeper.preparationEnd(run.id,answers,tile);if(d.ok){sfx?.work(d.mistakes?"odd":"cooked");setNote(`${name(d.made)} ×${d.n}${d.mistakes?th?" · ยังไม่สำเร็จ ลองเปลี่ยนวิธีเตรียมหรือระดับไฟ":" · Not quite right. Try another method or heat level.":th?" · จำการทดลองนี้ไว้แล้ว":" · Experiment remembered."}`);setRun(null);}else say(d.why);}finally{setPending(false);}}
 async function camp(action:"place"|"benefit",supply:string|null){if(!tile||pending)return;setPending(true);try{const d=await keeper.campDo(action,site,supply,tile,crypto.randomUUID());if(d.ok)setNote(action==="place"?th?"ตั้งค่ายแล้ว เพื่อนร่วมทางมาใช้ได้":"Camp set up; travelers can use it.":th?"เตรียมตัวแล้ว · ใช้เสบียง 1 ชิ้น แรง 1 แต้ม และโควตาค่าย 1 ครั้ง":"Preparation received · Used 1 supply, 1 stamina and 1 camp use.");else say(d.why);}finally{setPending(false);}}
 const c=keeper.camps().find(c=>c.site===site&&c.until>keeper.now()),ready=Object.keys(PREP_MAKES).filter(id=>tile&&preparationReady(p,id,tile)===null) as PrepId[];
 if(!active)return null;
 if(!open)return <TownFoot rank="chip"><button type="button" data-fieldwork-open onClick={()=>setOpen(true)} className="pressable pointer-events-auto min-h-11 rounded border-2 border-[#725533] bg-[#ede0bd] px-3 text-ui text-[#49361e]"><TownIcon name={station?"preparationTable":"fieldCamp"} size={28}/> {th?station?"ลองเตรียมวัตถุดิบ":"ที่พักริมทาง":station?"Try preparing ingredients":"A wayside resting place"}</button></TownFoot>;
 return <TownFoot rank="board"><section data-fieldwork-panel className={`${styles.panel} ${station?styles.kitchen:styles.camp} pointer-events-auto w-full max-w-[420px]`}>
  <header className="flex items-center gap-2"><TownIcon name={station?"preparationTable":"fieldCamp"} size={30}/><h2 className="font-display text-title">{th?station?"โต๊ะทดลองอาหาร":"พักและเตรียมตัว":station?"The preparation table":"Rest and prepare"}</h2><button type="button" onClick={()=>setOpen(false)} className="pressable ml-auto min-h-11 px-2">{th?"ปิด":"Close"}</button></header>
  {station&&!run&&<><p className="text-meta">{th?"ลองของที่มีอยู่ ดูสี กลิ่น และเสียงก่อนยกลง":"Try what you have. Read the colour, aroma and sound before finishing."}</p>{ready.map(id=><button type="button" data-preparation-begin={id} disabled={pending} onClick={()=>void begin(id)} key={id} className="pressable mt-2 w-full rounded border border-[#ae9669] bg-[#ddd3ad] p-2 text-left text-ui"><span>{p.prepBook?.includes(id)?name(id):th?"ลองเตรียมของชุดนี้":"Try this combination"}</span><small className="block text-meta">{PREP_MAKES[id].needs.map(([part,n])=>`${name(part)} ×${n}`).join(" · ")}</small></button>)}{ready.length===0&&<p className="py-3 text-ui">{th?"เขียง เครื่องครัว และวัตถุดิบที่เข้ากัน อาจทำให้เริ่มลองได้":"A preparation board, cookware and matching ingredients may open an experiment."}</p>}</>}
  {station&&run&&<div data-preparation-game>
   <p className="mb-2 text-meta">{th?`เลือกวิธีเตรียม ไฟ และจังหวะยกลง · ใช้วัตถุดิบเมื่อชิมและแรง ${PREPARATION.cost} แต้ม ถ้าพลาดจะได้ปุ๋ยหมัก`:`Choose method, heat and finish · Tasting spends the ingredients and ${PREPARATION.cost} stamina; mistakes yield compost.`}</p>
   <p className={styles.sectionLabel}>{th?"วัตถุดิบบนเขียง":"On the board"}</p>
   <div className={styles.prepTray}>{PREP_MAKES[run.recipe].needs.map(([id,n])=><span key={id}><TownIcon name={id as IconName} size={28}/>{name(id)} ×{n}</span>)}</div>
   <p className="text-meta">{th?"เป้าหมายเมื่อยกลง":"Finish at"}: {finish[PREPARATION.finish[run.recipe]][lang]}</p>
   <div className={styles.heatRead}><TownIcon name="preparationHeat" size={44}/><div><p className="text-ui">{finish[answers.finish][lang]}</p><p className="text-meta">{heat[answers.heat][lang]}</p><div className={styles.heatMeter} aria-hidden>{[0,1,2].map(i=><i key={i} data-lit={i<=answers.heat?"":undefined}/>)}</div></div></div>
   {held(p.bag,"scentLid")>0&&<p className="mt-2 text-meta">{th?"กลิ่นใต้ฝาครอบ":"Aroma beneath the lid"}: {answers.method===PREPARATION.methods[run.recipe]?(th?"กลิ่นวัตถุดิบเข้ากันแล้ว":"The ingredients' aromas have blended."):(th?"ยังมีกลิ่นดิบแยกกัน ลองเปลี่ยนวิธีเตรียม":"The raw aromas remain separate. Try another preparation method.")}</p>}
   {held(p.bag,"heatBell")>0&&<p role="status" className="text-meta">{answers.heat===PREPARATION.heat[run.recipe]?(th?"กระดิ่งนิ่ง · ไฟเข้าที่":"The bell settles; heat is steady."):(th?"กระดิ่งสั่น · ลองปรับไฟ":"The bell shakes; adjust the heat.")}</p>}
   {([['method',methods,th?"วิธีเตรียม":"Preparation"],['heat',heat,th?"ไฟ":"Heat"],['finish',finish,th?"จังหวะยกลง":"Finish"]] as const).map(([key,choices,label])=><fieldset key={key} className="mt-3"><legend className="text-ui">{label}</legend><div className="grid grid-cols-3 gap-1">{choices.map((word,i)=><button type="button" data-preparation-choice={`${key}:${i}`} key={i} onClick={()=>{sfx?.wake();sfx?.work(key==="method"?i===0?"knock":i===1?"scrub":"stir":key==="heat"?i===2?"crackle":i===1?"sizzle":"turn":i===1?"crackle":i===2?"stir":"down",.55);setAnswers(a=>({...a,[key]:i}));}} aria-pressed={answers[key]===i} className={`pressable min-h-12 rounded border p-1 text-meta ${answers[key]===i?"border-[#486348] bg-[#b8cd96]":"border-[#ae9669] bg-[#ddd3ad]"}`}>{word[lang]}</button>)}</div></fieldset>)}
   {(held(carriedBag(p),"tastingSpoon")>0||byOf("seasoning",levelOf(p,keeper.now(),"seasoning"))>0)&&<label className="mt-3 flex min-h-11 gap-2 text-ui"><input type="checkbox" checked={!!answers.correction} onChange={e=>setAnswers(a=>({...a,correction:e.target.checked}))}/>{th?"ชิมแล้วแก้หนึ่งจุด":"Taste and correct one decision"}</label>}
   <p className="text-meta">{held(p.bag,"cookTimer")>0?`${Math.max(0,Math.floor((keeper.now()-run.at)/1000))}s · `:""}{th?"เหลือเวลาทดลอง":"Experiment time remaining"} {Math.max(0,Math.ceil((run.until-keeper.now())/1000))}s</p>
   {keeper.now()>run.until?<><p role="status" className="mt-2 text-meta">{th?"หมดเวลาทดลองแล้ว วัตถุดิบยังอยู่ เริ่มลองใหม่ได้":"The experiment expired. Your ingredients are still yours; start a fresh attempt."}</p><button type="button" data-preparation-restart disabled={pending} onClick={()=>{setRun(null);setNote("");}} className="pressable mt-3 min-h-11 w-full rounded bg-[#486348] px-2 text-ui text-[#f6edcf]">{th?"กลับไปเลือกวัตถุดิบ":"Choose ingredients again"}</button></>:<button type="button" data-preparation-end disabled={pending||keeper.now()<run.at+PREPARATION.minMs} onClick={()=>void end()} className="pressable mt-3 min-h-11 w-full rounded bg-[#486348] px-2 text-ui text-[#f6edcf]">{th?"ยกลงและลองชิม":"Finish and taste"}</button>}
  </div>}
  {site>=0&&<div className="mt-3">{c?<><div className={styles.scene}><TownIcon name="fieldCamp" size={52}/><div><p className="font-display text-title">{th?"ค่ายพักริมทาง":"Wayside camp"}</p><p className={styles.caption}>{th?"ค่ายจะเก็บอีก":"Camp closes in"} {Math.max(0,Math.ceil((c.until-keeper.now())/60000))} {th?"นาที":"min"}</p></div></div><div className={styles.charges} aria-label={th?`เหลือใช้ร่วมกัน ${c.left} ครั้ง`:`${c.left} shared preparations left`}>{Array.from({length:c.left},(_,i)=><i key={i} aria-hidden/>)}<span className="text-ui">{th?"เหลือใช้ร่วมกัน":"Shared uses left"} {c.left}</span></div><p className="text-meta">{th?"ใช้เสบียง 1 ชิ้นและแรง 1 แต้มต่อครั้ง":"Each benefit uses 1 supply and 1 stamina"}</p><p className="text-meta">{th?"โควตาของคุณวันนี้":"Your daily allowance"}: {Math.max(0,CAMPS.daily-(p.campUses?.day===dayOf(keeper.now())?p.campUses.n:0))} / {CAMPS.daily}</p><p className={styles.sectionLabel}>{th?"เลือกสิ่งที่จะเตรียม":"Choose a preparation"}</p>{Object.keys(CAMPS.supplies).filter(id=>held(p.bag,id as ItemId)>0).map(id=>{const effect=WISH[CAMPS.supplies[id as keyof typeof CAMPS.supplies]];return <button type="button" key={id} data-camp-benefit={id} disabled={pending||c.left<=0} onClick={()=>void camp("benefit",id)} className={`${styles.supplyChoice} pressable mt-2 flex min-h-12 w-full items-center gap-3 rounded border border-[#8e9c77] bg-[#f0efdc] p-2 text-left text-ui`}><TownIcon name={id as IconName} size={34}/><span>{name(id as ItemId)} ×1<small className="block">{effect.name[th?"th":"en"]} · {effect.about[th?"th":"en"]}</small></span></button>;})}</>:<><div className={styles.scene}><TownIcon name="fieldCamp" size={60}/><p className="text-ui">{th?"พื้นที่โล่งสำหรับกางผ้า พัก และแบ่งเสบียงให้เพื่อนร่วมทาง":"A clear spot to pitch canvas, rest and share provisions with travelers."}</p></div>{held(p.bag,"campKit")>0?<button type="button" data-camp-place disabled={pending} onClick={()=>void camp("place",null)} className="pressable mt-2 min-h-12 w-full rounded border border-[#65784c] bg-[#4c6b48] p-2 text-ui text-[#faf2d6]">{th?"ตั้งค่าย":"Set up a camp"}<small className="block">{th?"ผ้าค่าย ×1 · เชื้อไฟ ×1 · เสบียง":"Canvas ×1 · Tinder ×1 · Rations"} ×{held(p.bag,"provisionChest")>0?5:3} · {th?"แรง":"Stamina"} {CAMPS.cost}</small></button>:<p className="text-meta">{th?"นำชุดตั้งค่าย ผ้าค่าย เชื้อไฟ และเสบียงมาที่นี่":"Bring a camp kit, canvas, tinder and rations here."}</p>}</>}</div>}
  {note&&<p role="status" className={`${styles.result} text-ui`}>{note}</p>}
  {!!p.prepBook?.length&&<TownNotebook title={th?"สมุดทดลองของฉัน":"My experiment notebook"} th={th} icon="recipes" entries={p.prepBook.filter(id=>id in PREP_MAKES).map(id=>{const r=PREP_MAKES[id as PrepId];return {key:id,title:name(id),icon:id as IconName,category:methods[PREPARATION.methods[id as PrepId]][lang],body:<><p>{th?"การทดลองที่ทำสำเร็จแล้ว":"A successful preparation experiment"}</p><ul>{r.needs.map(([part,n])=><li key={part} className="flex items-center gap-2"><TownIcon name={part as IconName} size={24}/>{name(part)} ×{n}</li>)}</ul><p>{th?"เครื่องครัว":"Cookware"}: {r.in.map(name).join(" · ")}</p><p>{methods[PREPARATION.methods[id as PrepId]][lang]} · {heat[PREPARATION.heat[id as PrepId]][lang]} · {finish[PREPARATION.finish[id as PrepId]][lang]}</p></>};})}/>}
 </section></TownFoot>;
}
