import {standIn} from './stand-in.mjs';
import {U} from './pglite-harness.mjs';
import {readFileSync} from 'node:fs';
await import('./repo-ts-town.mjs');
const {linesOf}=await import('@/lib/town/fishing');
const {newPurse}=await import('@/lib/town/trade');
const t=await standIn();
await t.runTwice(readFileSync(process.env.MIGRATION_FILE ?? process.env.FC_REPO+'/.claude/skills/fc-cash-town/scripts/db/v181_fishing_draft.sql','utf8'),'v181 fishing');
const one=async(s,p=[]) => (await t.sql(s,p)).rows[0];
for(const rod of ['rod','rodTeak','rodMaster']) for(const gift of [false,true]) {
 const purse={...newPurse(),bag:[{item:rod,n:1},{item:'worm',n:5},...Array(16).fill(null)],hand:rod,...(gift?{gifts:{had:['thingRod'],charms:[],familiar:null,used:{}}}:{})};
 const got=(await one('select town.line_count($1::jsonb) n',[JSON.stringify(purse)])).n;
 t.check(`${rod}, gift ${gift}: line count matches game`,got===linesOf(purse) && got===(rod==='rod'?1:2)+(gift?1:0),{got,want:linesOf(purse)});
}
const NOW=Date.now();
const purse={...newPurse(),coins:1000,bag:[{item:'rodMaster',n:1},{item:'worm',n:10},...Array(16).fill(null)],hand:'rodMaster'};
await t.sql('insert into public.town_purses(member_id,coins,doc) values($1::uuid,1000,$2::jsonb) on conflict(member_id) do update set coins=excluded.coins,doc=excluded.doc',[U.m1,JSON.stringify(purse)]);
const place=(await one("select p.key from public.town_catalog c, jsonb_each(c.data->'places') p where c.key='fishing' limit 1")).key;
const [x,y]=place.split(',').map(Number);
const cast=await t.as(U.m1,'select public.town_cast($1,$2,$3,false,\'pair\') r',['worm',x,y]);
t.check('tier 3 can cast two without owning gift',cast.rows?.[0]?.r.ok===true && cast.rows[0].r.line.lines===2,cast);
const line=(await one('select doc from public.town_lines where member_id=$1::uuid',[U.m1])).doc;
t.check('two independent catches stored',line.others.length===1,line);
t.check('bait count is charged for every line',(await one("select town.held(town.purse_of($1::uuid,false)->'bag','worm') n",[U.m1])).n===8);
await t.as(U.m1,"select public.town_land('left')");
const gifted={...purse,gifts:{had:['thingRod'],charms:[],familiar:null,used:{}}};
await t.sql('update public.town_purses set coins=1000,doc=$2::jsonb where member_id=$1::uuid',[U.m1,JSON.stringify(gifted)]);
const cast3=await t.as(U.m1,"select public.town_cast($1,$2,$3,false,'pair') r",['worm',x,y]);
t.check('gift adds a third real line',cast3.rows?.[0]?.r.ok===true && cast3.rows[0].r.line.lines===3,cast3);
t.check('three bait charges',(await one("select town.held(town.purse_of($1::uuid,false)->'bag','worm') n",[U.m1])).n===7);
const actual3=(await one('select doc from public.town_lines where member_id=$1::uuid',[U.m1])).doc;
t.check('three independent server catches',actual3.others.length===2,actual3);
await t.as(U.m1,"select public.town_land('left')");
const short={...gifted,bag:[{item:'rodMaster',n:1},{item:'worm',n:2},...Array(16).fill(null)]};
await t.sql('update public.town_purses set doc=$2::jsonb where member_id=$1::uuid',[U.m1,JSON.stringify(short)]);
const denied=await t.as(U.m1,"select public.town_cast($1,$2,$3,false,'pair') r",['worm',x,y]);
t.check('three lines refuse only two baits',denied.rows?.[0]?.r.ok===false,denied);
t.check('refused cast preserves bait',(await one("select town.held(town.purse_of($1::uuid,false)->'bag','worm') n",[U.m1])).n===2);
await t.sql('update public.town_purses set doc=$2::jsonb where member_id=$1::uuid',[U.m1,JSON.stringify(gifted)]);
await t.sql('insert into public.town_lines(member_id,doc) values($1::uuid,$2::jsonb)',[U.m1,JSON.stringify(actual3)]);
// Seed three fish as a cast that has just bitten: the server controls all three identities.
const three={...actual3,what:'tilapia',size:20,others:[{what:'carp',size:25},{what:'catfish',size:30}],bites_at:Date.now(),struck_at:null};
await t.sql('update public.town_lines set doc=$2::jsonb where member_id=$1::uuid',[U.m1,JSON.stringify(three)]);
const strike=await t.as(U.m1,'select public.town_strike(100) r');
t.check('one strike hooks all three',strike.rows?.[0]?.r.pair?.length===3,strike);
const landed=await t.as(U.m1,"select public.town_land('snapped','{\"which\":1}'::jsonb) r");
t.check('losing middle fish leaves the other two',landed.rows?.[0]?.r.more===true,landed);
const left=(await one('select doc from public.town_lines where member_id=$1::uuid',[U.m1])).doc;
t.check('identities remain in order',left.what==='tilapia' && left.others[0].what==='catfish',left);
const bad=await t.as(U.m1,"select public.town_land('landed','{\"which\":999}'::jsonb) r");
t.check('invalid line index changes nothing',bad.rows?.[0]?.r.ok===false,bad);
const untouched=(await one('select doc from public.town_lines where member_id=$1::uuid',[U.m1])).doc;
t.check('invalid index preserves both fish',JSON.stringify(left)===JSON.stringify(untouched),untouched);
for(const role of ['anon','authenticated'])t.check('count helper ACL stays private',(await one("select has_function_privilege($1,'town.line_count(jsonb)','EXECUTE') allowed",[role])).allowed===false);
for(const who of ['anon',U.m1])t.check('count helper stays private',!!(await t.as(who,"select town.line_count('{}'::jsonb)")).error);
t.done(); await t.db.close();
